import Navbar from '../components/Navbar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-[#8080FF] scrollbar'>
      <body className='bg-[#8080ff]'>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  )
}
