# Generated by Django 4.1.5 on 2023-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Civilii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "civilii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cseii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "cseii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cseiii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "cseiii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Itii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "itii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Itiii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "itiii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mctii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "mctii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mechii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "mechii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mechiii",
            fields=[
                ("sno", models.IntegerField(blank=True, db_column="SNo", null=True)),
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True,
                        db_column="RegisterNo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
                ("gender", models.TextField(blank=True, db_column="Gender", null=True)),
            ],
            options={
                "db_table": "mechiii",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "date",
                    models.TextField(
                        blank=True, db_column="DATE", primary_key=True, serialize=False
                    ),
                ),
                ("civil", models.TextField(blank=True, db_column="CIVIL", null=True)),
                ("cse", models.TextField(blank=True, db_column="CSE", null=True)),
                ("eee", models.TextField(blank=True, db_column="EEE", null=True)),
                ("ece", models.TextField(blank=True, db_column="ECE", null=True)),
                ("mech", models.TextField(blank=True, db_column="MECH", null=True)),
                ("mct", models.TextField(blank=True, db_column="MCT", null=True)),
                ("bme", models.TextField(blank=True, db_column="BME", null=True)),
                ("it", models.TextField(blank=True, db_column="IT", null=True)),
                ("aids", models.TextField(blank=True, db_column="AIDS", null=True)),
                ("csbs", models.TextField(blank=True, db_column="CSBS", null=True)),
            ],
            options={
                "db_table": "timetable",
                "managed": False,
            },
        ),
    ]
