# Generated by Django 4.1.5 on 2023-03-05 09:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buildings",
            fields=[
                (
                    "building_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("building_blocks", models.JSONField()),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.CreateModel(
            name="Degrees",
            fields=[
                (
                    "degree",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("degree_full_name", models.CharField(max_length=80)),
                ("degree_duration", models.IntegerField()),
            ],
            options={
                "verbose_name": "Degree",
                "verbose_name_plural": "Degrees",
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("branch", models.CharField(max_length=80)),
                (
                    "branch_short_name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("branch_code", models.CharField(max_length=10)),
                (
                    "degree",
                    models.ForeignKey(
                        default="UG",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="seats.degrees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "exam_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("from_data", models.DateField()),
                ("to_date", models.DateField()),
                ("departments", models.JSONField()),
                ("time_table", models.JSONField()),
                ("is_phd", models.BooleanField()),
                ("is_me", models.BooleanField()),
                ("is_years_together", models.BooleanField()),
                ("is_departments_together", models.BooleanField()),
                ("is_send_whatsapp_message", models.BooleanField()),
                ("time_to_send_whatsapp_message", models.TimeField()),
                ("no_of_sets", models.IntegerField()),
                (
                    "second_column_options",
                    models.CharField(
                        choices=[
                            ("Seat Number", "Seat Number"),
                            ("Set Code", "Set Code"),
                            ("Present/Absent", "Present/Absent"),
                        ],
                        default="Seat Number",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="Logos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="logos/")),
            ],
            options={
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
            },
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "room_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("room_floor", models.IntegerField()),
                ("room_strength", models.IntegerField(default=60)),
                ("room_block", models.CharField(blank=True, max_length=10)),
                (
                    "room_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="seats.buildings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="Years",
            fields=[
                ("year", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Year",
                "verbose_name_plural": "Years",
            },
        ),
        migrations.CreateModel(
            name="Templates",
            fields=[
                (
                    "template_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("number_of_rows", models.IntegerField()),
                ("number_of_columns", models.IntegerField()),
                ("room_strength", models.IntegerField()),
                ("is_single_seater", models.BooleanField()),
                ("is_boys_girls_separation", models.BooleanField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_alternate_dept_seated", models.BooleanField()),
                ("buildings", models.ManyToManyField(to="seats.buildings")),
                (
                    "logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="seats.logos"
                    ),
                ),
                ("rooms", models.ManyToManyField(to="seats.rooms")),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                ("subject_name", models.CharField(max_length=50)),
                (
                    "subject_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "subject_in_departments",
                    models.ManyToManyField(to="seats.departments"),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "register_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "ctype",
                    models.CharField(
                        choices=[("C", "Circuit"), ("N", "Non-Circuit"), ("P", "PhD")],
                        max_length=1,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="seats.degrees",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="seats.departments",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="seats.years"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="ScheduledMessages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("time", models.TimeField()),
                (
                    "to",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="seats.exams"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Message",
                "verbose_name_plural": "Scheduled Messages",
            },
        ),
        migrations.CreateModel(
            name="RoomData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rooms", models.JSONField()),
                ("ranges", models.JSONField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="seats.exams"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Data",
                "verbose_name_plural": "Room Data",
            },
        ),
        migrations.AddField(
            model_name="exams",
            name="exam_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="seats.templates"
            ),
        ),
        migrations.AddField(
            model_name="exams",
            name="phd_students",
            field=models.ManyToManyField(
                limit_choices_to={"ctype": "P"}, to="seats.students"
            ),
        ),
        migrations.AddField(
            model_name="exams",
            name="sets_for_which_subjects",
            field=models.ManyToManyField(to="seats.subjects"),
        ),
        migrations.AddField(
            model_name="exams",
            name="years",
            field=models.ManyToManyField(to="seats.years"),
        ),
    ]
