# Generated by Django 4.1.5 on 2023-01-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Civilii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Civil II",
                "verbose_name_plural": "Civil II",
            },
        ),
        migrations.CreateModel(
            name="Cseii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CSE II",
                "verbose_name_plural": "CSE II",
            },
        ),
        migrations.CreateModel(
            name="Cseiii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CSE III",
                "verbose_name_plural": "CSE III",
            },
        ),
        migrations.CreateModel(
            name="Itii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IT II",
                "verbose_name_plural": "IT II",
            },
        ),
        migrations.CreateModel(
            name="Itiii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IT III",
                "verbose_name_plural": "IT III",
            },
        ),
        migrations.CreateModel(
            name="Mctii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MCT II",
                "verbose_name_plural": "MCT II",
            },
        ),
        migrations.CreateModel(
            name="Mechii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name": "MECH II",
                "verbose_name_plural": "MECH II",
            },
        ),
        migrations.CreateModel(
            name="Mechiii",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MECH III",
                "verbose_name_plural": "MECH III",
            },
        ),
        migrations.CreateModel(
            name="NeededDocuments",
            fields=[
                (
                    "needed_documents_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("need_room_allotments", models.BooleanField()),
                ("need_notice_board_copies", models.BooleanField()),
                ("need_master_hall_plan", models.BooleanField()),
                ("need_attendance_sheets", models.BooleanField()),
                ("need_proforma_3", models.BooleanField()),
                ("need_proforma_4", models.BooleanField()),
                ("need_proforma_5", models.BooleanField()),
            ],
            options={
                "verbose_name": "Needed Documents",
                "verbose_name_plural": "Needed Documents",
            },
        ),
        migrations.CreateModel(
            name="RoomData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rooms", models.JSONField(blank=True, null=True)),
                ("ranges", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Room Data",
                "verbose_name_plural": "Room Data",
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "registerno",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("ctype", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("name", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateField(blank=True, primary_key=True, serialize=False),
                ),
                ("civil", models.TextField(blank=True, null=True)),
                ("cse", models.TextField(blank=True, null=True)),
                ("eee", models.TextField(blank=True, null=True)),
                ("ece", models.TextField(blank=True, null=True)),
                ("mech", models.TextField(blank=True, null=True)),
                ("mct", models.TextField(blank=True, null=True)),
                ("bme", models.TextField(blank=True, null=True)),
                ("it", models.TextField(blank=True, null=True)),
                ("aids", models.TextField(blank=True, null=True)),
                ("csbs", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Time Table",
                "verbose_name_plural": "Time Tables",
            },
        ),
        migrations.CreateModel(
            name="ExamTemplate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("template_name", models.CharField(max_length=200)),
                ("template_exam_name", models.CharField(max_length=200)),
                ("num_rows", models.IntegerField(default=5)),
                ("num_columns", models.IntegerField(default=6)),
                ("room_strength", models.IntegerField(default=60)),
                ("count_in_bench", models.IntegerField(default=2)),
                ("rooms", models.JSONField()),
                ("single_seater", models.BooleanField(default=False)),
                ("boys_girls_separation", models.BooleanField(default=False)),
                (
                    "needed_documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seats.neededdocuments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Template",
                "verbose_name_plural": "Exam Templates",
            },
        ),
    ]
