# Generated by Django 4.1.5 on 2023-02-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exam_name", models.CharField(max_length=200)),
                ("exam_fromdate", models.DateField()),
                ("exam_todate", models.DateField()),
                ("exam_depts", models.JSONField()),
                (
                    "exam_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seats.examtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
    ]
