# Generated by Django 4.1.5 on 2023-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("rows", models.IntegerField(blank=True, db_column="Rows")),
                ("columns", models.IntegerField(blank=True, db_column="Columns")),
                (
                    "room_strength",
                    models.IntegerField(blank=True, db_column="Room_Strength"),
                ),
                (
                    "count_in_bench",
                    models.IntegerField(blank=True, db_column="Count_in_Bench"),
                ),
                ("rooms", models.CharField(max_length=200)),
            ],
        ),
    ]
