# Generated by Django 4.1.5 on 2023-02-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examtemplate",
            name="template_exam_name",
        ),
    ]
