# Generated by Django 4.1.5 on 2023-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="ctype",
            field=models.CharField(
                choices=[("C", "Circuit"), ("N", "Non-Circuit"), ("P", "PhD")],
                default="C",
                max_length=1,
            ),
        ),
    ]
