# Generated by Django 4.1.5 on 2023-02-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examtemplate",
            name="needed_documents",
        ),
        migrations.RemoveField(
            model_name="examtemplate",
            name="single_seater",
        ),
    ]
