# Generated by Django 4.1.5 on 2023-03-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_departments_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exams",
            name="no_of_sets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exams",
            name="phd_students",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"ctype": "P"}, to="seats.students"
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="sets_for_which_subjects",
            field=models.ManyToManyField(blank=True, to="seats.subjects"),
        ),
        migrations.AlterField(
            model_name="exams",
            name="time_to_send_whatsapp_message",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
