# Generated by Django 4.1.5 on 2023-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="registerno",
            field=models.CharField(
                blank=True, max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
