# Generated by Django 4.1.5 on 2023-02-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_remove_examtemplate_template_exam_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="exam_depts",
            new_name="depts",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="exam_fromdate",
            new_name="fromdate",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="exam_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="exam_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="exam_template",
            new_name="template",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="exam_todate",
            new_name="todate",
        ),
    ]
