# Generated by Django 4.1.5 on 2023-01-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_alter_examtemplate_boys_girls_separation"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomdata",
            name="ranges",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
