# Generated by Django 4.1.5 on 2023-03-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0003_alter_exams_no_of_sets_alter_exams_phd_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="me_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="seats.rooms",
            ),
        ),
    ]
