# Generated by Django 4.1.5 on 2023-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0003_rename_exam_depts_exam_depts_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Timetable",
        ),
        migrations.AddField(
            model_name="exam",
            name="timetable",
            field=models.JSONField(null=True),
        ),
    ]
