# Generated by Django 4.1.5 on 2023-02-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0003_alter_students_registerno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examtemplate",
            name="count_in_bench",
        ),
        migrations.RemoveField(
            model_name="examtemplate",
            name="needed_documents",
        ),
    ]
