# Generated by Django 4.1.5 on 2023-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0003_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rooms", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
