# Generated by Django 4.1.5 on 2023-02-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0004_delete_timetable_exam_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomdata",
            name="exam",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="seats.exam"
            ),
        ),
    ]
