# Generated by Django 4.1.5 on 2023-01-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0004_roomdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtemplate",
            name="rooms",
            field=models.JSONField(blank=True, db_column="Rooms"),
        ),
    ]
