# Generated by Django 4.1.5 on 2023-03-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0004_exams_me_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="phd_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="phd_room",
                to="seats.rooms",
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="me_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="me_room",
                to="seats.rooms",
            ),
        ),
    ]
