# Generated by Django 4.1.5 on 2023-03-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0005_exams_phd_room_alter_exams_me_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomdata",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seats.exams"
            ),
        ),
    ]
