# Generated by Django 4.1.5 on 2023-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0005_roomdata_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="degree",
            field=models.CharField(blank=True, default="UG", max_length=5, null=True),
        ),
    ]
