# Generated by Django 4.1.5 on 2023-03-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0006_alter_roomdata_exam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exams",
            old_name="from_data",
            new_name="from_date",
        ),
    ]
