# Generated by Django 4.1.5 on 2023-02-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0007_departments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Departments",
        ),
    ]
