# Generated by Django 4.1.5 on 2023-02-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0008_delete_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("branch", models.CharField(max_length=200)),
                ("branch_short_name", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("branch_code", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
