# Generated by Django 4.1.5 on 2023-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0008_exams_departments_left_exams_departments_right"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="girls_rooms",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="exams",
            name="minimum_students_in_room",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="exams",
            name="randomize_every_n_rooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exams",
            name="rooms_order",
            field=models.JSONField(default=dict),
        ),
    ]
