# Generated by Django 4.1.5 on 2023-02-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0009_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buildings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("building_name", models.CharField(max_length=200)),
                ("building_blocks", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_no", models.CharField(max_length=200)),
                ("room_floor", models.CharField(max_length=200)),
                ("room_strength", models.IntegerField(default=60)),
                ("room_block", models.CharField(max_length=200)),
                (
                    "room_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="seats.buildings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
    ]
