# Generated by Django 4.1.5 on 2023-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0009_exams_girls_rooms_exams_minimum_students_in_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="strictly_divide_buildings",
            field=models.BooleanField(default=False),
        ),
    ]
