# Generated by Django 4.1.5 on 2023-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0010_exams_strictly_divide_buildings"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="is_common_room_strength",
            field=models.BooleanField(default=False),
        ),
    ]
