# Generated by Django 4.1.5 on 2023-02-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0010_buildings_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Years",
            fields=[
                ("year", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "degree",
                    models.CharField(
                        choices=[("UG", "UG"), ("PG", "PG"), ("PHD", "PHD")],
                        default="UG",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Year",
                "verbose_name_plural": "Years",
            },
        ),
    ]
