# Generated by Django 4.1.5 on 2023-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0011_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="years",
            name="degree",
        ),
        migrations.AlterField(
            model_name="years",
            name="year",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
