# Generated by Django 4.1.5 on 2023-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0013_exam_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtemplate",
            name="buildings",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="rooms",
            field=models.JSONField(default={}),
        ),
    ]
