# Generated by Django 4.1.5 on 2023-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0014_examtemplate_buildings_alter_examtemplate_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtemplate",
            name="buildings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="rooms",
            field=models.JSONField(default=dict),
        ),
    ]
